# Generated by Django 4.2.16 on 2024-11-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transgram.documents.validators_document


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/', validators=[transgram.documents.validators_document.document_file_size])),
                ('cmr', models.FileField(blank=True, null=True, upload_to='cmrs/', validators=[transgram.documents.validators_document.document_file_size])),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='additional_docs/', validators=[transgram.documents.validators_document.document_file_size])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
